### ISSUE TITLE
TypeError when ran train.py

### ISSUE THREAD

**Issue by kj-lai** [arvind385801/paraphraseGen#1]
Hi, when i ran `train.py` it returns this error

```
[root @ ~]$ python2.7 train.py --num-iterations 140000
preprocessed data was found and loaded
preprocessed data was found and loaded
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    cross_entropy, kld, coef = train_step(iteration, args.batch_size, args.use_cuda, args.dropout, start_index)
  File "./paraphraseGen/model/rvae.py", line 124, in train
    input = [Variable(t.from_numpy(var)) for var in input]
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.
```

**Comment by soni-sarvesh** [comment]
It worked for me (I used Python 3).

**Comment by kj-lai** [comment]
Noted, thanks for the advice.
